pyCharm/DjangoTest/projects/mysite/config/urls.py
from django.contrib import admin
from django.urls import include, path
from index import views as index_views
from pybo.views import base_views
from balance import views as balance_views
from django.conf.urls import url
from chartapp import views
# from modelpage import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('main_index', base_views.index, name='index'),  # '/' 에 해당되는 path
    path('index/', index_views.main_views),
    path('balance/', balance_views.main_view),
    path('samsung.share/',views.main_page),
    path('data.json/',views.data_json),
    path('data2.json/', views.data2_json),
    path('samsung.volume/', views.main_page2),
    path('data3.json/', views.data3_json),
    path('cos/', views.main_page3),
    path('', include('nameapp.urls', namespace='nameapp')),
    path('index_main', index_views.main_tests),
    path('menu_test', index_views.menu_views),
    # path('modelpage', modelpage.runmodel),
]

pyCharm/DjangoTest/projects/mysite/nameapp/urls.py
from django.urls import path

from nameapp import views

app_name = 'nameapp'

urlpatterns = [
    path('chart', views.ChartView.as_view(), name="chart"),
    path('api/predict/', views.KospiPredictAPIView.as_view(), name="predict_kospi_api"),
    path('api/result/', views.ResultAPIView.as_view(), name="result_api"),
    path('chart_main', views.tests.as_view(), name='chart_main'),

    path('chart2', views.ChartView2.as_view(), name="chart2"),
    path('api/predict2/', views.KospiPredict2APIView.as_view(), name="predict_kospi_api2"),
    path('api/result2/', views.ResultAPIView2.as_view(), name="result_api2"),
    path('', views.titletest, name="titletest"),

]


pyCharm/DjangoTest/projects/mysite/pybo/urls.py
from django.urls import path


from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
# base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
    # ---------------------------------------------------------------------------------------- #

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pyCharm/DjangoTest/projects/mysite/nameapp/models.py
from django.db import models

# Create your models here.
class KospiPredict(models.Model):
    date = models.DateField(max_length=10, null=False, unique=True)
    close = models.IntegerField(null=True)
    open = models.IntegerField(null=True)

    class Meta:
        managed = False
        db_table = 'jebal'

class KospiPredict2(models.Model):
    date = models.DateField(max_length=10, null=False, unique=True)
    close = models.IntegerField(null=True)
    open = models.IntegerField(null=True)

    class Meta:
        managed = False
        db_table = 'jestest'

pyCharm/DjangoTest/projects/mysite/nameapp/views.py
from nameapp.models import KospiPredict
from nameapp.models import KospiPredict2
from rest_framework.response import Response
from rest_framework.views import APIView
from django.views.generic import View
from django.shortcuts import render
from time import mktime, strptime

class ResultAPIView(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request):
        data = request.session.get('result')
        return Response(data)


class KospiPredictAPIView(APIView):

    authentication_classes = []
    permission_classes = []

    def get(self, request):
        stocks = KospiPredict.objects.all().order_by('date')

        close_list = []
        open_list = []
        for stock in stocks:
            time_tuple = strptime(str(stock.date), '%Y-%m-%d %H:%M:%S')
            utc_now = mktime(time_tuple) * 1000
            close_list.append([utc_now, stock.close])
            open_list.append([utc_now, stock.open])

        data = {
            'close': close_list,
            'open': open_list
        }

        return Response(data)

class ChartView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'nameapp/chart.html')

class tests(View):
    def main_tests(request):
        return render(request, 'nameapp/maintest.html')


class ResultAPIView2(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request):
        data2 = request.session.get('result2')
        return Response(data2)


class KospiPredict2APIView(APIView):

    authentication_classes = []
    permission_classes = []

    def get(self, request):
        stocks = KospiPredict2.objects.all().order_by('date')

        close_list = []
        open_list = []
        for stock in stocks:
            time_tuple = strptime(str(stock.date), '%Y-%m-%d')
            utc_now = mktime(time_tuple) * 1000
            close_list.append([utc_now, stock.close])
            open_list.append([utc_now, stock.open])

        data2 = {
            'close': close_list,
            'open': open_list
        }

        return Response(data2)

class ChartView2(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'nameapp/chart2.html')

def titletest(request):
    return render(request, 'nameapp/title.html')



pyCharm/DjangoTest/projects/mysite/nameapp/templates/nameapp/chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div id="container">

  <script src="https://code.highcharts.com/stock/highstock.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>

    function setChart() {
      Highcharts.setOption({
        global: {
          useUTC: false
        }
      });
    };

    $.ajax({
      url: "{% url 'nameapp:predict_kospi_api' %}",
      dataType: 'json',
      success: function (data) {

        Highcharts.setOptions({
          global: {
            useUTC: false
          }
        });

        Highcharts.stockChart("container", {

          chart: {
            height: 500
          },

          title: {
            text: 'SAMSUNG Etc'
          },

          rangeSelector: {
            selected: 5,
            inputEnabled: false
          },

          xAxis: {
            type: 'datetime',
            labels:{
              formatter: function(){
                return Highcharts.dateFormat('%y.%m.%d', this.value);
              },
              step: 3
            }
          },

          yAxis: {
            labels: {
              format: '{value}p',
              style: {
                color: 'rgba(0,0,0,.6)',
              },
              x: 30,
            },
            opposite: false,
            tickInterval: 50,
          },

          tooltip: {
            xDateFormat: '%Y-%m-%d',
            split: true
          },

          series: [{
              name: '시가',
              data: data.open,
              color: 'rgba(0,200,0,.6)',
              lineWidth: 2
          },
          {
              name: '종가',
              data: data.close,
              lineWidth: 3
          }],

          legend: {
            enabled: true,
            align: 'left',
            verticalAlign: 'top',
            floating: true,
            x: 30,
            y: 70
          },

          responsive: {
            rules: [{
              condition: {
                maxWidth: 600
              },
              chartOptions: {
                chart: {
                  height: 300
                },
                navigator: {
                  enabled: false
                }
              }
            }]
          }
        });
      }
    });

  </script>
</div>

</body>
</html>

pyCharm/DjangoTest/projects/mysite/nameapp/templates/nameapp/chart2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div id="container">

  <script src="https://code.highcharts.com/stock/highstock.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>

    function setChart() {
      Highcharts.setOption({
        global: {
          useUTC: false
        }
      });
    };

    $.ajax({
      url: "{% url 'nameapp:predict_kospi_api2' %}",
      dataType: 'json',
      success: function (data) {

        Highcharts.setOptions({
          global: {
            useUTC: false
          }
        });

        Highcharts.stockChart("container", {

          chart: {
            height: 500
          },

          title: {
            text: 'LG Chem'
          },

          rangeSelector: {
            selected: 5,
            inputEnabled: false
          },

          xAxis: {
            type: 'datetime',
            labels:{
              formatter: function(){
                return Highcharts.dateFormat('%y.%m.%d', this.value);
              },
              step: 3
            }
          },

          yAxis: {
            labels: {
              format: '{value}p',
              style: {
                color: 'rgba(0,0,0,.6)',
              },
              x: 30,
            },
            opposite: false,
            tickInterval: 50,
          },

          tooltip: {
            xDateFormat: '%Y-%m-%d',
            split: true
          },

          series: [{
              name: '시가',
              data: data.open,
              color: 'rgba(0,200,0,.6)',
              lineWidth: 2
          },
          {
              name: '종가',
              data: data.close,
              lineWidth: 3
          }],

          legend: {
            enabled: true,
            align: 'left',
            verticalAlign: 'top',
            floating: true,
            x: 30,
            y: 70
          },

          responsive: {
            rules: [{
              condition: {
                maxWidth: 600
              },
              chartOptions: {
                chart: {
                  height: 300
                },
                navigator: {
                  enabled: false
                }
              }
            }]
          }
        });
      }
    });

  </script>
</div>

</body>
</html>

pyCharm/DjangoTest/projects/mysite/nameapp/templates/nameapp/maintest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <frameset rows="10%, 75%, 15%" frameborder="1">
        <frame src="nameapp/title.html">
        <frameset cols="20%, 80%">
            <frame src="">
            <frame src="" name="right">
        </frameset>
        <frame src="">
    </frameset>
    <title>Title</title>
</head>
<body>

</body>
</html>

pyCharm/DjangoTest/projects/mysite/nameapp/templates/nameapp/title.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
            <style type ="text/css">
                body {
                background: white url('https://cdn.crowdpic.net/list-thumb/thumb_l_E45CD27CAB2BA20B826005BC74A00E5C.jpg') no-repeat fixed 50% 50%/50% 50%;
                }
            </style>
    </head>
<body>
    <div id="title">
        <ul>
            <st>
                <h2> Share Community </h2>
                <h3> <a href="http://localhost:8000/index_main">Let's go to the Main Page</a></h3>
            </st>
        </ul>

</body>
</html>